### ISSUE TITLE
InvalidAudienceError: Invalid audience with azuread_tenant

### ISSUE THREAD

**Issue by pmarzouk** [python-social-auth/social-core#227]
I got the following exception when using the azuread_tenant backend:

```
ERROR Internal Server Error: /accounts/complete/azuread-tenant-oauth2/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/weblate/accounts/views.py", line 193, in demo_wrap
    return function(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/weblate/accounts/views.py", line 910, in social_complete
    return complete(request, backend)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_django/views.py", line 33, in complete
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/actions.py", line 41, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/utils.py", line 252, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/backends/oauth.py", line 405, in auth_complete
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/utils.py", line 252, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/backends/oauth.py", line 410, in do_auth
    data = self.user_data(access_token, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_core/backends/azuread_tenant.py", line 112, in user_data
    audience=self.setting('SOCIAL_AUTH_AZUREAD_OAUTH2_KEY')
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jwt.py", line 89, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jwt.py", line 125, in _validate_claims
    self._validate_aud(payload, audience)
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jwt.py", line 174, in _validate_aud
    raise InvalidAudienceError('Invalid audience')
InvalidAudienceError: Invalid audience
```

The code tries to use the wrong setting to verify the audience element from the JWT token.
It uses SOCIAL_AUTH_AZUREAD_OAUTH2_KEY instead of SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY.

I worked around it by adding a setting SOCIAL_AUTH_AZUREAD_OAUTH2_KEY with the same value as SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY.

**Comment by omab** [comment]
This is already fixed by fb7eabd318b6839ce5cb6329b2ca77205f21a493
