### ISSUE TITLE
Unable to install due to python3-openid

### ISSUE THREAD

**Issue by assembledadam** [python-social-auth/social-core#314]
```shell
Collecting python3-openid>=3.0.10; python_version >= "3.0" (from social-auth-core>=1.2.0->social-auth-app-django>=0.1.0->django-rest-framework-social-oauth2->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/bd/de/52c5699f52dcee3037db587196dcaf63ffedf5fbeba3183afe9b21a3a89f/python3_openid-3.1.0-py3-none-any.whl (130kB)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6.6/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6.6/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/usr/lib/python3.6.6/lib/python3.6/site-packages/pip/_internal/wheel.py", line 886, in build
    assert have_directory_for_build
AssertionError
```

**Comment by assembledadam** [comment]
Sorted.

For anyone else:
Problem was not related to python3-openid, was actually a bug in pip when installing from requirements using --no-cache-dir, see https://github.com/pypa/pip/issues/6158
