### ISSUE TITLE
ShopifyAPI v5 breaking

### ISSUE THREAD

**Issue by wesferr** [python-social-auth/social-core#364]
On version 5.0.* of ShopifyAPI is necessary a version of API on Session method

`ERROR:django.request:Internal Server Error: /oauth/login/shopify/
Traceback (most recent call last):
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/social_django/views.py", line 23, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/social_core/actions.py", line 27, in do_auth
    return backend.start()
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/social_core/backends/base.py", line 35, in start
    return self.strategy.redirect(self.auth_url())
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/social_core/backends/shopify.py", line 58, in auth_url
    session = self.shopifyAPI.Session(self.data.get('shop').strip())
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/shopify/session.py", line 47, in __init__
    self.version = ApiVersion.coerce_to_version(version)
  File "/home/hd/Estagio/muambator/env/local/lib/python2.7/site-packages/shopify/api_version.py", line 18, in coerce_to_version
    raise VersionNotFoundError
`

**Comment by omab** [comment]
Fixed by #353 and released on `3.2.0`.
