### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by atodorov** [python-social-auth/social-core#412]
@omab  I am working on several customized backends for my application and I get the following exceptions when I try to import a backend to inherit from. 

```
>>> from social_core.backends.github import GithubOAuth2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/social_core/backends/github.py", line 5, in <module>
    from requests import HTTPError
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 71, in <module>
    import email.parser
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/social_core/backends/email.py", line 5, in <module>
    from .legacy import LegacyAuth
ImportError: attempted relative import with no known parent package
```

Our kerberos backend has a slightly different import resulting in the same issue:
```
>>> from social_core.exceptions import AuthException
>>> from social_core.backends.base import BaseAuth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/social_core/backends/base.py", line 3, in <module>
    from requests import request, ConnectionError
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 71, in <module>
    import email.parser
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/social_core/backends/email.py", line 5, in <module>
    from .legacy import LegacyAuth
ImportError: attempted relative import with no known parent package
```

**Comment by atodorov** [comment]
Resolved in social-auth-core==3.2.0, I had the previous version. Sorry for the noise.
