### ISSUE TITLE
Discord social auth does not work anymore

### ISSUE THREAD

**Issue by j4m3s-s** [python-social-auth/social-core#504]
### Expected behaviour
Login should work instead of having an exception. 

### Actual behaviour
Gives out an exception instead of completing logging.

### What are the steps to reproduce this issue?
Create an application that connects to discord using social auth.
Calling discord API fails.

### Error Log
```
Traceback (most recent call last):
2020-09-15T01:27:19.628991797Z   File "/usr/local/lib/python3.8/site-packages/social_core/utils.py", line 251, in wrapper
2020-09-15T01:27:19.629015418Z     return func(*args, **kwargs)
2020-09-15T01:27:19.629034192Z   File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 395, in auth_complete
2020-09-15T01:27:19.629053455Z     response = self.request_access_token(
2020-09-15T01:27:19.629071684Z   File "/usr/local/lib/python3.8/site-packages/social_core/backends/oauth.py", line 373, in request_access_token
2020-09-15T01:27:19.629090095Z     return self.get_json(*args, **kwargs)
2020-09-15T01:27:19.629108276Z   File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 238, in get_json
2020-09-15T01:27:19.629126850Z     return self.request(url, *args, **kwargs).json()
2020-09-15T01:27:19.629145135Z   File "/usr/local/lib/python3.8/site-packages/social_core/backends/base.py", line 234, in request
2020-09-15T01:27:19.629163718Z     response.raise_for_status()
2020-09-15T01:27:19.629182042Z   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
2020-09-15T01:27:19.629251810Z     raise HTTPError(http_error_msg, response=self)
2020-09-15T01:27:19.629272201Z requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://discord.com/api/v6/oauth2/token

```

**Comment by j4m3s-s** [comment]
Apparently we just had a wrong token. Closing this.
