### ISSUE TITLE
VK oauth2 deprecated api version

### ISSUE THREAD

**Issue by Lomank123** [python-social-auth/social-core#621]
### Deprecated api version
Faced this issue recently. Versions below 5.81 are deprecated. Can you fix this?

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/auth/complete/vk-oauth2/?redirect_state=BKSi211sYf7EIqVHUm3fgzlqUC4LZplT&code=5fd565ba126521b858&state=BKSi211sYf7EIqVHUm3fgzlqUC4LZplT

Django Version: 3.2.8
Python Version: 3.9.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'coreapp',
 'crispy_forms',
 'rest_framework',
 'corsheaders',
 'social_django',
 'easy_thumbnails',
 'django_cleanup',
 'storages']
Installed Middleware:
['whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/social_django/utils.py", line 46, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/social_django/views.py", line 31, in complete
    return do_complete(request.backend, _do_login, user=request.user,
  File "/py/lib/python3.9/site-packages/social_core/actions.py", line 45, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/social_core/utils.py", line 248, in wrapper
    return func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/social_core/backends/oauth.py", line 391, in auth_complete
    return self.do_auth(response['access_token'], response=response,
  File "/py/lib/python3.9/site-packages/social_core/utils.py", line 248, in wrapper
    return func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/social_core/backends/oauth.py", line 397, in do_auth
    data = self.user_data(access_token, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/social_core/backends/vk.py", line 118, in user_data
    raise AuthException(self, msg)

Exception Type: AuthException at /auth/complete/vk-oauth2/
Exception Value: Invalid request: versions below 5.81 are deprecated. Version param should be passed as "v". "version" param is invalid and not supported. For more information go to https://vk.com/dev/constant_version_updates
```

**Comment by nijel** [comment]
Already fixed by https://github.com/python-social-auth/social-core/pull/613
