### ISSUE TITLE
Error with open_id_connect.py new groups user_details clashing with Django auth user and groups

### ISSUE THREAD

**Issue by tommyli** [python-social-auth/social-core#690]
When upgrading from 4.2.0 to 4.3.0, we hit the following error message.

Exception message `Direct assignment to the forward side of a many-to-many set is prohibited. Use groups.set() instead.`

After [comparing](https://github.com/python-social-auth/social-core/compare/4.2.0...4.3.0) and some investigation, I noticed this [new line](https://github.com/python-social-auth/social-core/blob/20abe2a49e91a63479d72a2b91f4446b630ad375/social_core/backends/open_id_connect.py#L251) is the culprit.  I feel this change is a bit intrusive given Django auth is widely used and `groups` attribute name is already taken.  As a workaround, I've put below in our settings.py.

```python
SOCIAL_AUTH_PROTECTED_USER_FIELDS = ['groups']
```

For refrence, stacktrace below.

```text
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/homebrew/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/app/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/social_django/utils.py", line 46, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/app/lib/python3.8/site-packages/social_django/views.py", line 31, in complete
    return do_complete(request.backend, _do_login, user=request.user,
  File "/app/lib/python3.8/site-packages/social_core/actions.py", line 45, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/app/lib/python3.8/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/social_core/utils.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/social_core/backends/oauth.py", line 401, in auth_complete
    return self.do_auth(response['access_token'], response=response,
  File "/app/lib/python3.8/site-packages/social_core/utils.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/social_core/backends/oauth.py", line 413, in do_auth
    return self.strategy.authenticate(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/social_django/strategy.py", line 105, in authenticate
    return authenticate(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/app/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 76, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/app/lib/python3.8/site-packages/social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/app/lib/python3.8/site-packages/social_core/backends/base.py", line 83, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/app/lib/python3.8/site-packages/social_core/backends/base.py", line 113, in run_pipeline
    result = func(*args, **out) or {}
  File "/app/lib/python3.8/site-packages/social_core/pipeline/user.py", line 119, in user_details
    setattr(user, name, value)
  File "/app/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 545, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use groups.set() instead.
```

**Comment by nijel** [comment]
The assignment to `groups` AFAIR worked in Django before 2.0, but I'm still not sure if it ever worked this way (this contains strings, not a group objects).

https://github.com/python-social-auth/social-core/pull/692 should fix this. It was introduced in https://github.com/python-social-auth/social-core/pull/669 by @candlerb

**Comment by Poslovitch** [comment]
I encounter a similar issue with the Mediawiki connector, with a similar line:
https://github.com/python-social-auth/social-core/blob/20abe2a49e91a63479d72a2b91f4446b630ad375/social_core/backends/mediawiki.py#L173

Should I open another issue?
